### ISSUE TITLE
I want to Update Readme file

### ISSUE THREAD

**Issue by SOMNATH0904** [CareerDevelopmentHub/Beginner_WeatherAPP#9]
As per your readme file it is mentioned that if further any changes i have to do then i have to discuss with the owner of this repo ... Previously, I have added a pull request for updating the Readme file ... but before updating i had not read that first i have to raise a issue for that ... So, Can i Update the README file ...

**Comment by PandaAnshuman** [comment]
Updating the readme file will not be accepted
